### PR TITLE
View for Login Usecase

### PR DESCRIPTION
**Pull request by vrindasubhash**
Implemented all files for the login view. 

Need to integrate the success view once the user preferences view is made. 

Had a main method for testing, was deleted before merging in. 

Screenshot 2023-11-26 at 2 13 22 PM
Screenshot 2023-11-26 at 2 13 39 PM

### CODE REVIEW

**Comment by stefanateljevic04** [comment]
Everything looks good

**Comment by stefanateljevic04** [comment]
Can you add screenshot of what the view looks like?

**Comment by vrindasubhash** [comment]
@stefanateljevic04 Yes! Added screenshots of what the login view looks like and what happens when the login fails.

**Review by stefanateljevic04 — APPROVED** [review]
Your naming conventions make sense, the package structure adheres our project standard, and your overall coding style is clear and easy to read. 

As you have included multiple screenshots of your view, it is clear that it is functional. A good next step would be to write some frontend tests with full coverage to handle any edge cases.  

With your presenter, state, viewmodel and view, you have adhered to clean architecture. I am seeing no violations of any solid principles, such as high level modules depending on low level ones. They are depending on abstractions. 

I am not seeing any Javadoc for your public methods, so it will be important to add those in a future pull request. 

Your description is clear and concise, and your commit message provide sufficient information if we would need to revert to previous states. Overall, good job!

**Review by samaslanowicz — COMMENTED** [review]
great

**Review by jackkfan0305 — COMMENTED** [review]
Fantastic!

**Review by samaslanowicz — APPROVED** [review]
thanks for updating your prepare success view, merging in now

**Pull request merged**
