### PR TITLE
Updating UserPreference Entity

### PR DESCRIPTION
**Pull request by merrickliu888**
Updated Entities to be in line with the User Preferences required by the GenerateMealUseCase:

- Removed dietPreference
- Removed cuisinePreference
- Added dishType
- Renamed healthPreferences to health
- Changed all "<...>Preference" types to "String".

### CODE REVIEW

**Comment by merrickliu888** [comment]
@samaslanowicz Once this is merged in. You are going to have to update your SavePreferencesUseCase.

**Comment by jackkfan0305** [comment]
looks good

**Comment by samaslanowicz** [comment]
looks fine, I do think we should maybe name it something other than "health." That seems pretty vague, what options will we have in the list for that?

**Comment by merrickliu888** [comment]
@samaslanowicz Your right, I'll change that.

**Review by jackkfan0305 — APPROVED** [review]
Everything looks good!

**Review by samaslanowicz — COMMENTED** [review]
yep that seems fine

**Review by samaslanowicz — COMMENTED** [review]
yep that seems fine

**Pull request merged**
