### PR TITLE
Generate meal controller

### PR DESCRIPTION
**Pull request by merrickliu888**
### Overview
- Finished the GenerateMealController. @jackkfan0305 could you review. Let me know if there is any changes that need to be made for your part.
### Controller Specifics
- Controller takes in these paramters from view: `List<String> healthPreferences, List<String> mealType, List<String> dishType, int calMin, int calMax, int carbMin, int carbMax, int proteinMin, int proteinMax, int fatMin, int fatMax`
- Note that the nutrient ranges are not passed in as `Range` objects, rather the `Range` objects are instantiated with the min and max parameters of the controller.
- Unlike the actual `UserPreferences` class, here I did not make a class similar to `NutrientRange` to hold each nutrient `Range`.

### CODE REVIEW

**Review by jackkfan0305 — CHANGES_REQUESTED** [review]
Most of the things look good but I do have a few things to point out though. First, I feel like its better if we use the Range class instead of passing both min and max as parameters. And second, I recommend you to make a package named generateMeals and put this file in that package so later on it's more organized when other people start making PRs for their own controllers. But other than that everything looks good. Lmk if you have any feedbacks.

**Comment by merrickliu888** [comment]
Ok. Just to clarify, are you saying put a separate "generate_meals" package within the "interface_adapters" package, or just create a "generate_meals" package that includes "interface_adapters" and the other components of CA.

Also for the "Range" class, I was thinking about that, but the issue was that in Clean Architecture, Interface Adapters can't access Entities as its two layers "below" it. So I saw two solutions:

1. Redefine a Range Class in the interface_adapters or some other higher level package
2. Instantiate the Range objects in the constructor of the input data, as input_dat is part of the use_case which can access entities.

Regardless, I'm actually going to ask on Piazza about this.

**Comment by merrickliu888** [comment]
This was my question on Piazza:[https://piazza.com/class/lm84a7mo56k5wy/post/1094]( https://piazza.com/class/lm84a7mo56k5wy/post/1094)

**Comment by jackkfan0305** [comment]
I meant creating a seperate "generate_meals" package within the "interface_adapters" package, similar to what I did for useCase: 

Screen Shot 2023-11-07 at 12 06 17 PM

**Comment by merrickliu888** [comment]
I did that. 
image

**Comment by jackkfan0305** [comment]
> I did that. image

oh wait yes my bad.

**Review by jackkfan0305 — APPROVED** [review]
Looks good!

**Pull request merged**
