### PR TITLE
GeneratMeals Sequence Diagram

### PR DESCRIPTION
**Pull request by jackkfan0305**
Screen Shot 2023-10-30 at 5 43 32 PM

I think we should add back the Meal class we deleted earlier because we could then have a cleaner output data (a meal class rather than a bunch of parameters). 

@merrickliu888 lmk if there are any questions/concerns

### CODE REVIEW

**Comment by jackkfan0305** [comment]
Forgot to add input data in my sequence diagram, need to fix

**Comment by merrickliu888** [comment]
@jackkfan0305 I agree. But it shouldn't go in entities, it should be in the same folder as the usecase like in the CA homework we did.

**Comment by jackkfan0305** [comment]
> @jackkfan0305 I agree. But it shouldn't go in entities, it should be in the same folder as the usecase and be InputData like in the CA homework we did.

Good point.  I'm gonna change the diagram and add inputData and have a bunch of getters to get the input data. Then I will call the constructor of Meal class directly to make the class and then pass the meal class as the output data.

**Comment by jackkfan0305** [comment]
Screen Shot 2023-10-30 at 6 18 49 PM

@merrickliu888 updated the new sequence diagram.

**Review by merrickliu888 — APPROVED** [review]
Looks good. If we need to make changes we can always do so in the future!

**Pull request merged**
