### PR TITLE
Entities

### PR DESCRIPTION
**Pull request by merrickliu888**
Created a UML diagram representing the Entities of the application, and created Java Classes representing them.

Questions:
- Because our MVP does not include saving meals, do we even need the "Meal" class and classes and attributes associated with it?
entities

### CODE REVIEW

**Comment by stefanateljevic04** [comment]
As we are aiming for our MVP, it makes sense to remove the "Meal" class for the time being. If needed we can add it later 👍

**Comment by jackkfan0305** [comment]
I agree with Merrick because we only need to display the receipe/ingredients. If we have time then we can add it later

**Comment by vrindasubhash** [comment]
Maybe we can take it out for now, but later if we want to add the Save Meal use case we can add it back.

**Comment by samaslanowicz** [comment]
looks good to me!

**Comment by merrickliu888** [comment]
@jackkfan0305 just made those changes could you review them.

**Pull request merged**
