### PR TITLE
FileDataAccessObject

### PR DESCRIPTION
**Pull request by merrickliu888**
**Overview of Changes:**
- Finished FileUserDataAccessObject
- Implemented and Updated UserFactory and CommonUserFactory
- Updated some entities and uml diagram

**Specifics:**
- Created one `save()` method which saves everything in memory, which simplifies things by removing the `savePreferences` method.

**Things to look out for:**
- See if your useCase needs any additional methods here. Please let me know!

### CODE REVIEW

**Review by samaslanowicz — COMMENTED** [review]
Seems fine to me. The save() and create() methods appears to be correct, and it seems that we're on the same page with the UserPreference class

**Review by vrindasubhash — COMMENTED** [review]
Everything looks good to me. Good style and implementations adhere to CA!

**Review by jackkfan0305 — APPROVED** [review]
Everything looks good. Just one question, I created a GenerateMealsDataAccessInterface interface, and I'm assuming your FileDataAccessObject will implement mine and the other data access interfaces?

**Comment by stefanateljevic04** [comment]
@merrickliu888 In FileUserDataAccessObject.java, can you please add a method called create_user that I would be able to use for the signup use case?

**Review by stefanateljevic04 — CHANGES_REQUESTED** [review]
@merrickliu888 In FileUserDataAccessObject.java, can you please add a method called create_user that I would be able to use for the signup use case?

**Review by stefanateljevic04 — APPROVED** [review]
Changes made, nice

**Pull request merged**
