### PR TITLE
added a new directory to store all the sequence diagrams for each use…

### PR DESCRIPTION
**Pull request by samaslanowicz**
Screen Shot 2023-10-30 at 2 24 00 PM
added a new directory to store all the sequence diagrams for each use case and added the sequence diagram for save preferences to the directory

### CODE REVIEW

**Comment by samaslanowicz** [comment]
@vrindasubhash can you review these changes?

**Comment by vrindasubhash** [comment]
The new directory looks good Sam!

**Comment by jackkfan0305** [comment]
great addition, makes files more organized

**Review by vrindasubhash — APPROVED** [review]
New directory looks good, approving the merge.

**Pull request merged**
